### ISSUE TITLE
runv-containerd panics under pressure test

### ISSUE THREAD

**Issue by WeiZhang555** [hyperhq/runv#292]
runv-containerd panics after started 3000 containers.

panic logs:

```
panic: send on closed channel

goroutine 1866548 [running]:
panic(0x9376c0, 0xc9f6e4fcd0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/hyperhq/runv/hypervisor.waitInitAck(0xc85bb7cd80, 0xc8c2050040)
    /home/darcy/gocode/src/github.com/hyperhq/runv/hypervisor/init_comm.go:325 +0x25e
created by github.com/hyperhq/runv/hypervisor.waitCmdToInit
    /home/darcy/gocode/src/github.com/hyperhq/runv/hypervisor/init_comm.go:179 +0x103
```

**Comment by laijs** [comment]
the hyperstart code in runv was refactored.
