### ISSUE TITLE
protect pseudoTtys.ttys 

### ISSUE THREAD

**Issue by laijs** [hyperhq/runv#393]
```
2016/12/07 07:27:19 http: response.WriteHeader on hijacked connection
I1207 07:27:19.188134   24432 tty.go:439] a stdin closed, read unix /var/run/hyper.sock->@: use of closed network connection
fatal error: concurrent map read and map write

goroutine 1147 [running]:
runtime.throw(0x135a17d, 0x21)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:566 +0x95 fp=0xc42114fde8 sp=0xc42114fdc8
runtime.mapaccess2_fast64(0x118ad40, 0xc4210b3290, 0x1, 0x1116620, 0xc420683cf0)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/hashmap_fast.go:156 +0x1b1 fp=0xc42114fe10 sp=0xc42114fde8
github.com/hyperhq/runv/hypervisor.(*pseudoTtys).connectStdin.func1(0xc42107a680, 0x1, 0xc420645c70)
	/home/travis/gopath/src/github.com/hyperhq/hyperd/Godeps/_workspace/src/github.com/hyperhq/runv/hypervisor/tty.go:448 +0x736 fp=0xc42114ff98 sp=0xc42114fe10
```

**Comment by laijs** [comment]
fixed by libhyperstart
