### ISSUE TITLE
tty panic: concurrent map read and map write

### ISSUE THREAD

**Issue by gnawux** [hyperhq/runv#420]
http://ci.hyper.sh:8080/job/hyperd-auto/96/console

```
I0112 02:57:47.218967    7012 tty.go:125] session 3 closed by peer, close pty
I0112 02:57:47.218983    7012 tty.go:162] Close tty 
I0112 02:57:47.219021    7012 tty.go:123] tty: read 0 bytes for stream 5
I0112 02:57:47.219037    7012 tty.go:125] session 5 closed by peer, close pty
I0112 02:57:47.219049    7012 tty.go:162] Close tty 
I0112 02:57:47.219129    7012 tty.go:271] a stdin closed, io: read/write on closed pipe
fatal error: concurrent map read and map write
I0112 02:57:47.219286    7012 tty.go:271] a stdin closed, io: read/write on closed pipe

goroutine 288 [running]:
runtime.throw(0x1362704, 0x21)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc421290e20 sp=0xc421290e00
runtime.mapaccess2_fast64(0x1192820, 0xc42098def0, 0x3, 0xc420010120, 0xc4207fe900)
	/usr/local/go/src/runtime/hashmap_fast.go:156 +0x1b1 fp=0xc421290e48 sp=0xc421290e20
github.com/hyperhq/runv/hypervisor.(*pseudoTtys).startStdin.func1(0xc42095cf40, 0x3, 0xc4214815a0)
	/home/jenkins/workspace/hyperd-auto/Godeps/_workspace/src/github.com/hyperhq/runv/hypervisor/tty.go:279 +0x4d8 fp=0xc421290f98 sp=0xc421290e48
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc421290fa0 sp=0xc421290f98
created by github.com/hyperhq/runv/hypervisor.(*pseudoTtys).startStdin
	/home/jenkins/workspace/hyperd-auto/Godeps/_workspace/src/github.com/hyperhq/runv/hypervisor/tty.go:294 +0xea
```

**Comment by gnawux** [comment]
The file has already gone in the latest master...
