### ISSUE TITLE
Failed qemu startup blocks supervisord indefinitely

### ISSUE THREAD

**Issue by wrouesnel** [hyperhq/runv#423]
If the QEMU VM process fails to startup in `qemu_process.go` (in this case due to be intentionally breaking the kernel load) then `runv` gets blocked indefinitely on a signal. This appears to be due to a mismatch between the event protocol and use of GenericOperation structs.

The problem is in qemu_process.go there's a lot of structs like this when qemu fails:
```go
glog.Errorf("open pid file failed: %v", err)
			ctx.Hub <- &hypervisor.VmStartFailEvent{Message: "open pid file failed"}
			return
```

But at this point in the startup process, `vm.go` is stuck in these two functions:
```go
func (vm *Vm) SendGenericOperation(name string, op func(ctx *VmContext, result chan<- error), states ...string) <-chan error {
	result := make(chan error, 1)
	goe := &GenericOperation{
		OpName: name,
		State:  states,
		OpFunc: op,
		Result: result,
	}
	vm.Hub <- goe
	return result
}

func (vm *Vm) GenericOperation(name string, op func(ctx *VmContext, result chan<- error), states ...string) error {
	return <-vm.SendGenericOperation(name, op, states...)
}
```

Which deadlocks the response code, despite a VmStartFailEvent having been emitted. The generic operation result means that ctx.Hub is never read.

This locks up docker and anything higher up the stack in the event of any VM start failure (a pretty likely event).

Log:
```
I0116 15:19:21.135371   20870 server.go:41] gRPC handle CreateContainer
I0116 15:19:21.137280   20870 hyperpod.go:460] Using kernel: ; Initrd: ; vCPU: 1; Memory 128
I0116 15:19:21.179076   20870 hyperpod.go:472] Creating VM with default kernel config
I0116 15:19:21.179413   20870 qemu_process.go:131] cmdline arguments: -machine pc-i440fx-2.0,accel=kvm,usb=off -global kvm-pit.lost_tick_policy=discard -cpu host -kernel /home/will/src/go/src/github.com/hyperhq/hyperstart/build/kernel -initrd /home/will/src/go/src/github.com/hyperhq/hyperstart/build/hyper-initrd.img -append console=ttyS0 panic=1 no_timer_check -realtime mlock=off -no-user-config -nodefaults -no-hpet -rtc base=utc,driftfix=slew -no-reboot -display none -boot strict=on -m 128 -smp 1 -qmp unix:/var/run/hyper/vm-ZOdcKYHGNN/qmp.sock,server,nowait -serial unix:/var/run/hyper/vm-ZOdcKYHGNN/console.sock,server,nowait -device virtio-serial-pci,id=virtio-serial0,bus=pci.0,addr=0x2 -device virtio-scsi-pci,id=scsi0,bus=pci.0,addr=0x3 -chardev socket,id=charch0,path=/var/run/hyper/vm-ZOdcKYHGNN/hyper.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charch0,id=channel0,name=sh.hyper.channel.0 -chardev socket,id=charch1,path=/var/run/hyper/vm-ZOdcKYHGNN/tty.sock,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=2,chardev=charch1,id=channel1,name=sh.hyper.channel.1 -fsdev local,id=virtio9p,path=/var/run/hyper/vm-ZOdcKYHGNN/share_dir,security_model=none -device virtio-9p-pci,fsdev=virtio9p,mount_tag=share_dir -daemonize -pidfile /var/run/hyper/vm-ZOdcKYHGNN/pidfile -D /var/log/hyper/qemu/vm-ZOdcKYHGNN.log
I0116 15:19:21.179449   20870 qemu_process.go:132] qemu log file: /var/log/hyper/qemu/vm-ZOdcKYHGNN.log
I0116 15:19:22.107109   20870 vm_console.go:18] connected to /var/run/hyper/vm-ZOdcKYHGNN/console.sock
I0116 15:19:22.107138   20870 qmp_handler.go:167] connected to /var/run/hyper/vm-ZOdcKYHGNN/qmp.sock
I0116 15:19:22.107177   20870 qmp_handler.go:177] begin qmp init...
I0116 15:19:22.107189   20870 vm_console.go:25] connected /var/run/hyper/vm-ZOdcKYHGNN/console.sock as telnet mode.
I0116 15:19:22.107111   20870 init_comm.go:106] Wating for init messages...
I0116 15:19:22.107109   20870 tty.go:111] tty socket connected
I0116 15:19:22.182374   20870 vm_console.go:63] Input byte chan closed, close the output string chan
I0116 15:19:22.182471   20870 vm_console.go:36] SB[vm-ZOdcKYHGNN] console output end
E0116 15:19:22.182472   20870 init_comm.go:66] read init data failed
E0116 15:19:22.183231   20870 init_comm.go:110] read init message failed... read unix @->/var/run/hyper/vm-ZOdcKYHGNN/hyper.sock: read: connection reset by peer
I0116 15:19:22.183274   20870 hypervisor.go:29] vm vm-ZOdcKYHGNN: main event loop got message 18(ERROR_INIT_FAIL)
E0116 15:19:22.182470   20870 tty.go:62] read tty data failed
E0116 15:19:22.183308   20870 vm_states.go:286] SB[vm-ZOdcKYHGNN] read init message failed... read unix @->/var/run/hyper/vm-ZOdcKYHGNN/hyper.sock: read: connection reset by peer
E0116 15:19:22.183334   20870 vm_states.go:216] Shutting down because of an exception: connection to vm broken
I0116 15:19:22.183343   20870 vm_states.go:219] SB[vm-ZOdcKYHGNN] poweroff vm based on command: connection to vm broken
I0116 15:19:22.183311   20870 tty.go:118] tty socket closed, quit the reading goroutine read unix @->/var/run/hyper/vm-ZOdcKYHGNN/tty.sock: read: connection reset by peer
I0116 15:19:22.183400   20870 tty.go:87] tty chan closed, quit sent goroutine
E0116 15:19:22.182502   20870 qmp_handler.go:181] get qmp welcome failed: read unix @->/var/run/hyper/vm-ZOdcKYHGNN/qmp.sock: read: connection reset by peer
E0116 15:19:22.183476   20870 qmp_handler.go:361] QMP initialize failed
E0116 15:19:22.184421   20870 qemu_process.go:148] qemu: could not load kernel '/home/will/src/go/src/github.com/hyperhq/hyperstart/build/kernel': No such file or directory
E0116 15:19:22.184438   20870 qemu_process.go:152] exit status 1
```

Stack:
```
goroutine 6 [running]:
main.Stack(0xc42002b768, 0x414885, 0x8c5040)
	/home/will/src/go/src/github.com/hyperhq/runv/main.go:66 +0x79
main.PrintStack()
	/home/will/src/go/src/github.com/hyperhq/runv/main.go:58 +0x22
main.main.func1(0xc4200143c0)
	/home/will/src/go/src/github.com/hyperhq/runv/main.go:82 +0x73
created by main.main
	/home/will/src/go/src/github.com/hyperhq/runv/main.go:84 +0x83

goroutine 1 [chan receive]:
github.com/hyperhq/runv/containerd.daemon(0xc4201c2510, 0xc4201f4150, 0x2e, 0xc4201f4150, 0x2e)
	/home/will/src/go/src/github.com/hyperhq/runv/containerd/containerd.go:149 +0x270
github.com/hyperhq/runv/containerd.glob..func1(0xc42000ca00)
	/home/will/src/go/src/github.com/hyperhq/runv/containerd/containerd.go:128 +0x609
reflect.Value.call(0x8c7fc0, 0x9e07b8, 0x13, 0x9918d5, 0x4, 0xc420143538, 0x1, 0x1, 0x4b6ee8, 0x984ee0, ...)
	/home/will/opt/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0x8c7fc0, 0x9e07b8, 0x13, 0xc420143538, 0x1, 0x1, 0x996a6f, 0xc420143518, 0x4ba636)
	/home/will/opt/go/src/reflect/value.go:302 +0xa4
github.com/hyperhq/runv/vendor/github.com/codegangsta/cli.HandleAction(0x8c7fc0, 0x9e07b8, 0xc42000ca00, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/github.com/codegangsta/cli/app.go:482 +0x1e0
github.com/hyperhq/runv/vendor/github.com/codegangsta/cli.Command.Run(0x997181, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9ad4af, 0x32, 0x0, ...)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/github.com/codegangsta/cli/command.go:186 +0xc26
github.com/hyperhq/runv/vendor/github.com/codegangsta/cli.(*App).Run(0xc4201e2000, 0xc420096140, 0x13, 0x14, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/github.com/codegangsta/cli/app.go:235 +0x60c
main.main()
	/home/will/src/go/src/github.com/hyperhq/runv/main.go:156 +0xc23

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/will/opt/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 4 [syscall]:
os/signal.signal_recv(0xe0e4c0)
	/home/will/opt/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/home/will/opt/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/home/will/opt/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 5 [chan receive]:
github.com/hyperhq/runv/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0xe28320)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/github.com/golang/glog/glog.go:882 +0x7a
created by github.com/hyperhq/runv/vendor/github.com/golang/glog.init.1
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/github.com/golang/glog/glog.go:410 +0x21d

goroutine 7 [select, locked to thread]:
runtime.gopark(0x9e1c18, 0x0, 0x993c7e, 0x6, 0x18, 0x2)
	/home/will/opt/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42002bf30, 0x0, 0x18)
	/home/will/opt/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42002bf30)
	/home/will/opt/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/home/will/opt/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/home/will/opt/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 8 [chan receive]:
github.com/hyperhq/runv/supervisor.(*Supervisor).reaper(0xc4201c2510)
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/supervisor.go:120 +0xcd
created by github.com/hyperhq/runv/supervisor.New
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/supervisor.go:50 +0x258

goroutine 9 [chan receive]:
github.com/hyperhq/runv/supervisor.(*SvEvents).setupEventLog.func1(0xc420014660, 0xc4201c2540, 0xc42013bb80)
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/events.go:55 +0x86
created by github.com/hyperhq/runv/supervisor.(*SvEvents).setupEventLog
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/events.go:64 +0x1e5

goroutine 22 [IO wait]:
net.runtime_pollWait(0x7f837f39bff8, 0x72, 0x0)
	/home/will/opt/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4200700d0, 0x72, 0xc42004bdb0, 0xc4200780b0)
	/home/will/opt/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4200700d0, 0xe0b7c0, 0xc4200780b0)
	/home/will/opt/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).accept(0xc420070070, 0x0, 0xe09bc0, 0xc4201254c0)
	/home/will/opt/go/src/net/fd_unix.go:419 +0x238
net.(*UnixListener).accept(0xc4201253a0, 0x441e2e, 0xc42004be70, 0x54d8b9)
	/home/will/opt/go/src/net/unixsock_posix.go:158 +0x32
net.(*UnixListener).Accept(0xc4201253a0, 0x9e1198, 0xc4200ae120, 0xe13540, 0xc4200981c8)
	/home/will/opt/go/src/net/unixsock.go:229 +0x49
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).Serve(0xc4200ae120, 0xe100c0, 0xc4201253a0, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:277 +0x15a
github.com/hyperhq/runv/containerd.startServer.func1(0xc4201f4150, 0x2e, 0xc4200ae120, 0xe100c0, 0xc4201253a0)
	/home/will/src/go/src/github.com/hyperhq/runv/containerd/containerd.go:193 +0xd5
created by github.com/hyperhq/runv/containerd.startServer
	/home/will/src/go/src/github.com/hyperhq/runv/containerd/containerd.go:196 +0x167

goroutine 23 [IO wait]:
net.runtime_pollWait(0x7f837f39bf38, 0x72, 0x7)
	/home/will/opt/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc4200701b0, 0x72, 0xc42003a8c8, 0xc4200780b0)
	/home/will/opt/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc4200701b0, 0xe0b7c0, 0xc4200780b0)
	/home/will/opt/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc420070150, 0xc42027c000, 0x8000, 0x8000, 0x0, 0xe0b7c0, 0xc4200780b0)
	/home/will/opt/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc4200981c8, 0xc42027c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/home/will/opt/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc4200746c0)
	/home/will/opt/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).Read(0xc4200746c0, 0xc4200a81b8, 0x9, 0x9, 0x44e6a0, 0xc42012f140, 0x0)
	/home/will/opt/go/src/bufio/bufio.go:209 +0x1bc
io.ReadAtLeast(0xe07e40, 0xc4200746c0, 0xc4200a81b8, 0x9, 0x9, 0x9, 0xc42003aad8, 0x4603b0, 0xc420018640)
	/home/will/opt/go/src/io/io.go:307 +0xa4
io.ReadFull(0xe07e40, 0xc4200746c0, 0xc4200a81b8, 0x9, 0x9, 0xc42012f140, 0x0, 0x1)
	/home/will/opt/go/src/io/io.go:325 +0x58
github.com/hyperhq/runv/vendor/golang.org/x/net/http2.readFrameHeader(0xc4200a81b8, 0x9, 0x9, 0xe07e40, 0xc4200746c0, 0x0, 0xc400000000, 0xc42003ac70, 0x69110f)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/golang.org/x/net/http2/frame.go:237 +0x7b
github.com/hyperhq/runv/vendor/golang.org/x/net/http2.(*Framer).ReadFrame(0xc4200a8180, 0x276, 0x276, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/golang.org/x/net/http2/frame.go:464 +0xa4
github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport.(*framer).readFrame(0xc42016ea20, 0xc42029bbc0, 0xc42029bbc0, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport/http_util.go:406 +0x2f
github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc4200ae1b0, 0xc42016eab0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport/http2_server.go:243 +0x1ef
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).serveStreams(0xc4200ae120, 0xe12b80, 0xc4200ae1b0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:350 +0x160
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc4200ae120, 0xe13540, 0xc4200981c8, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:337 +0x3da
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).handleRawConn(0xc4200ae120, 0xe13540, 0xc4200981c8)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:314 +0x422
created by github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).Serve
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:286 +0x1a9

goroutine 24 [select]:
github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport.(*http2Server).controller(0xc4200ae1b0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport/http2_server.go:652 +0x597
created by github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport.newHTTP2Server
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/transport/http2_server.go:134 +0x6bf

goroutine 35 [chan receive]:
github.com/hyperhq/runv/containerd/api/grpc/server.(*apiServer).Events(0xc4200981b8, 0xc420138800, 0xe12a60, 0xc42012e840, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/containerd/api/grpc/server/server.go:159 +0x131
github.com/hyperhq/runv/vendor/github.com/docker/containerd/api/grpc/types._API_Events_Handler(0x95a340, 0xc4200981b8, 0xe11aa0, 0xc420146480, 0x0, 0x30)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/github.com/docker/containerd/api/grpc/types/api.pb.go:1345 +0x117
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).processStreamingRPC(0xc4200ae120, 0xe12b80, 0xc4200ae1b0, 0xc42015e0e0, 0xc4201253e0, 0xdfb540, 0xc42029a030, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:602 +0x705
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200ae120, 0xe12b80, 0xc4200ae1b0, 0xc42015e0e0, 0xc42029a030)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:686 +0xc33
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420256060, 0xc4200ae120, 0xe12b80, 0xc4200ae1b0, 0xc42015e0e0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:348 +0xab
created by github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:349 +0xa3

goroutine 45 [chan receive]:
github.com/hyperhq/runv/hypervisor.(*Vm).GenericOperation(0xc4202eae00, 0x997861, 0xb, 0x9e0820, 0xc420350a20, 0x2, 0x2, 0xc42013f658, 0xc42013f501)
	/home/will/src/go/src/github.com/hyperhq/runv/hypervisor/vm.go:739 +0xaa
github.com/hyperhq/runv/hypervisor.(*Vm).Kill(0xc4202eae00)
	/home/will/src/go/src/github.com/hyperhq/runv/hypervisor/vm.go:324 +0xa2
github.com/hyperhq/runv/supervisor.createHyperPod(0xe0e200, 0xc4201ee0c0, 0xc420161520, 0x1, 0x80, 0x200, 0x8ae800, 0xc4201616a8)
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/hyperpod.go:503 +0xa9d
github.com/hyperhq/runv/supervisor.(*Supervisor).getHyperPod.func1(0xc4201c2510, 0xc42013f8c8, 0xc42013f8d0, 0xc420161520)
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/supervisor.go:192 +0x9e
github.com/hyperhq/runv/supervisor.(*Supervisor).getHyperPod(0xc4201c2510, 0xc4202ea740, 0x40, 0xc420161520, 0x0, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/supervisor.go:193 +0x1a9
github.com/hyperhq/runv/supervisor.(*Supervisor).CreateContainer(0xc4201c2510, 0xc4202ea740, 0x40, 0xc420146a00, 0x7d, 0xc42030e000, 0x88, 0xc42030e090, 0x89, 0xc42030e120, ...)
	/home/will/src/go/src/github.com/hyperhq/runv/supervisor/supervisor.go:57 +0xe3
github.com/hyperhq/runv/containerd/api/grpc/server.(*apiServer).CreateContainer(0xc4200981b8, 0x7f837c29e080, 0xc42029bc80, 0xc420296480, 0x0, 0x271, 0x271)
	/home/will/src/go/src/github.com/hyperhq/runv/containerd/api/grpc/server/server.go:55 +0x29c
github.com/hyperhq/runv/vendor/github.com/docker/containerd/api/grpc/types._API_CreateContainer_Handler(0x95a340, 0xc4200981b8, 0x7f837c29e080, 0xc42029bc80, 0xc4202ea400, 0x0, 0x0, 0xc420166c10, 0x41eb8e, 0xc420166be0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/github.com/docker/containerd/api/grpc/types/api.pb.go:1184 +0x27d
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200ae120, 0xe12b80, 0xc4200ae1b0, 0xc42015e8c0, 0xc4201253e0, 0xe00778, 0xc42029bc50, 0x0, 0x0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:522 +0xa14
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).handleStream(0xc4200ae120, 0xe12b80, 0xc4200ae1b0, 0xc42015e8c0, 0xc42029bc50)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:682 +0x6ad
github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc420256060, 0xc4200ae120, 0xe12b80, 0xc4200ae1b0, 0xc42015e8c0)
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:348 +0xab
created by github.com/hyperhq/runv/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/home/will/src/go/src/github.com/hyperhq/runv/vendor/google.golang.org/grpc/server.go:349 +0xa3

```

**Comment by wrouesnel** [comment]
I chased this down a little more - the exact problem is that processes sending GenericOperations can block indefinitely if the VmContext.loop() function exits because the vm.Hub channel is never drained. As a result a process is left with an outstanding GenericOperation in progress that doesn't return a result.

The immediate fix is to have the loop termination auto-fail all commands/operations which are sent to it before it exits, but that leaves open the issue that a badly behaved communicator could keep trying to send failing commands.
